# Generated by Django 4.1.2 on 2022-11-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='details',
            field=models.CharField(max_length=200),
        ),
    ]
