# Generated by Django 4.1.2 on 2022-11-25 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_features_productname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='productName',
        ),
        migrations.AddField(
            model_name='features',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='features',
            name='details',
            field=models.CharField(max_length=30),
        ),
    ]
