# Generated by Django 4.1.2 on 2022-12-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_features_productname_features_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='details',
            field=models.CharField(max_length=500),
        ),
    ]
